"use client";
// import type { Metadata } from "next";
import AuthProvider from "./context/AuthProvider";
import { Box, Typography } from "@mui/material";
import Sidebar from "./components/NavBar";
import MainContainer from "./components/MainContainer";
import AppBar, { Navigation } from "./components/AppBar";
import { options } from "./api/auth/[...nextauth]/options";
import { getServerSession } from "next-auth/next";
import Link from "next/link";
import LandingPage from "./components/LandingPage";
import CommonTheme from "./components/MuiTheme";
// export const metadata: Metadata = {
//   title: "DOCKWAVE STORE",
//   description: "To upload and store important files",
// };

// export default async function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   const session = await getServerSession(options);
//   return (
//     <>
//       {session ? (
//         <AuthProvider>
//           <Box sx={{ display: "flex", height: "100%" }}>
//             <Box sx={{ display: { xs: "none", md: "block" } }}>
//               <Sidebar />
//             </Box>
//             <Box
//               sx={{
//                 flex: 1,
//                 backgroundColor:
//                   CommonTheme.palette.mode === "light" ? "f8f8f8" : "#121212",
//               }}
//             >
//               <AppBar user={session?.user} pagetype={""} />
//               <MainContainer>{children}</MainContainer>
//             </Box>
//           </Box>
//         </AuthProvider>
//       ) : (
//         <>
//           <LandingPage />
//         </>
//       )}
//     </>
//   );
// }
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(options);
  return (
    <>
      {session ? (
        <AuthProvider>
          <Box sx={{ display: "flex", height: "100%" }}>
            <Box sx={{ display: { xs: "none", md: "block" } }}>
              <Sidebar />
            </Box>
            <Box
              sx={{
                flex: 1,
                backgroundColor:
                  CommonTheme.palette.mode === "light" ? "f8f8f8" : "black",
                height: "100%",
              }}
            >
              <AppBar user={session?.user} pagetype={""} />
              <MainContainer>{children}</MainContainer>
            </Box>
          </Box>
        </AuthProvider>
      ) : (
        <>
          <LandingPage />
        </>
      )}
    </>
  );
}
